### ISSUE TITLE
Another Gatsby Develop Fails

### ISSUE THREAD

**Issue by JDubbTX** [bagseye/barcadia#44]
I have imported the example content into my free Contentful account.  New to Gatsby and Contentful - perhaps this is too big a bite for me...  Any help with this?

````
jweirich@LAPTOP-97G89Q4N:~/projects/barcadia$ gatsby develop
success load gatsby config - 0.036s
success load plugins - 0.529s
success onPreInit - 0.006s
success initialize cache - 0.050s
success copy gatsby files - 0.291s
success Compiling Gatsby Functions - 0.132s
success onPreBootstrap - 0.143s
success createSchemaCustomization - 0.183s
success Contentful: Sync changed items - 0.075s - 1/1 13.38/s
info Contentful: 0 new/updated entries
info Contentful: 0 deleted entries
info Contentful: 15 cached entries
info Contentful: 0 new/updated assets
info Contentful: 25 cached assets
info Contentful: 0 deleted assets
success Contentful: Fetch data (s1oiqlt103tb-master) - 0.256s
info Creating 3 Contentful Page nodes
info Creating 4 Contentful Post nodes
info Creating 5 Contentful Product nodes
info Creating 3 Contentful FAQ nodes
info Creating 25 Contentful asset nodes
success Contentful: Create nodes (s1oiqlt103tb-master) - 0.053s
success Contentful: Process data (s1oiqlt103tb-master) - 0.166s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.585s
success building schema - 0.588s
success createPages - 0.001s
success createPagesStatefully - 0.229s
info Total nodes: 97, SitePage nodes: 17 (use --verbose for breakdown)
success Checking for changed pages - 0.004s
success write out redirect data - 0.009s
success onPostBootstrap - 0.007s
info bootstrap finished - 4.205s
success onPreExtractQueries - 0.003s

 ERROR 

(node:155803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners
added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)


 ERROR 

(node:155803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners
added to [PassThrough]. Use emitter.setMaxListeners() to increase limit


 ERROR 

(node:155803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners
added to [PassThrough]. Use emitter.setMaxListeners() to increase limit


 ERROR 

(node:155803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners
added to [PassThrough]. Use emitter.setMaxListeners() to increase limit


 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "references" on type "ContentfulPostContent".

If you don't expect "references" to exist on the type "ContentfulPostContent" it is most likely a typo.
However, if you expect "references" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please
try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL
 explorer to see which fields you can query and what shape they have
- You want to optionally use your field "references" and right now it is not used anywhere. Therefore
Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with
 that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you
don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for
"ContentfulPostContent":
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization#creating-type-definitions

File: src/pages/news/{contentfulPost.url}.js:25:9

failed extract queries from components - 3.066s
success write out requires - 0.007s
success run page queries - 0.009s - 1/1 114.39/s
warn Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({
'lib/mappings.wasm': ... }) before using SourceMapConsumer

File: .cache/app.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({
'lib/mappings.wasm': ... }) before using SourceMapConsumer

File: .cache/polyfill-entry.js

failed Building development bundle - 9.132s
ERROR in ./.cache/app.js
Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 
'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/home/jweirich/projects/barcadia/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/home/jweirich/projects/barcadia/node_modules/source-map/lib/wasm.js:25:16)
    at /home/jweirich/projects/barcadia/node_modules/source-map/lib/source-map-consumer.js:264:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object._loader
(/home/jweirich/projects/barcadia/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:81:9)

ERROR in ./.cache/polyfill-entry.js
Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 
'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/home/jweirich/projects/barcadia/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/home/jweirich/projects/barcadia/node_modules/source-map/lib/wasm.js:25:16)
    at /home/jweirich/projects/barcadia/node_modules/source-map/lib/source-map-consumer.js:264:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object._loader
(/home/jweirich/projects/barcadia/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:81:9)

develop compiled with 2 errors
success Writing page-data.json files to public directory - 0.165s - 3/17 103.14/s
```

**Comment by capsj** [comment]
Hey I recently came across this same issue. Seems its related to newer versions of node, fixed it by defining:

```
export NODE_OPTIONS="--no-experimental-fetch"
```
